# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: nightly

on:
  workflow_dispatch:
    inputs:
      pre-built-kamel-image:
        description: 'Kamel image url for skipping building of kamel stages. Used for debugging'
        required: false
      skip-test-suites:
        description: 'List of test suites to skip (values: BUILDER,KUBERNETES,KNATIVE,UPGRADE). Used for debugging'
        required: false
      save-failed-test-ns:
        description: 'Do NOT delete any failed test namespaces (sets CAMEL_K_TEST_SAVE_FAILED_TEST_NAMESPACE)'
        required: false
        default: true
      skip-problematic:
        description: 'Whether tests marked as problematic should be skipped - true by default (sets CAMEL_K_TEST_SKIP_PROBLEMATIC)'
        required: false
        default: true
      test-filters:
        description: |
          List of comma-separated key/value pairs to filter the tests in each test suite:
            TEST_INTEGRATION_COMMON_RUN,        TEST_INTEGRATION_COMMON_BUILD_RUN, TEST_INTEGRATION_COMMON_CLI_RUN
            TEST_INTEGRATION_COMMON_CONFIG_RUN, TEST_INTEGRATION_COMMON_LANG_RUN,  TEST_INTEGRATION_COMMON_TRAITS_RUN
            TEST_SERVICE_RUN,                   TEST_QUARKUS_RUN,                  TEST_KUSTOMIZE_RUN
            TEST_BUILDER_RUN,                   TEST_KNATIVE_RUN,                  TEST_UPGRADE_RUN
        required: false
  schedule:
    - cron: "0 18 * * *"
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  integration-tests:

    runs-on: ubuntu-20.04
    steps:

    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Convert input parameters to env vars
      shell: bash
      run: |
        ./.github/workflows/nightly-process-inputs.sh \
          -i "${{ github.event.inputs.pre-built-kamel-image }}" \
          -n "${{ github.event.inputs.save-failed-test-ns }}" \
          -s "${{ github.event.inputs.skip-test-suites }}" \
          -p "${{ github.event.inputs.skip-problematic }}" \
          -t "${{ github.event.inputs.test-filters }}"

    - name: Checkout Camel-k
      uses: actions/checkout@v2
      with:
        repository: '${{ secrets.E2E_UPSTREAM_REPOSITORY }}'
        ref: '${{ secrets.E2E_UPSTREAM_BRANCH }}'
        path: '.'
        persist-credentials: false
        submodules: recursive

    - name: Upgrade Tests
      if: ${{ always() && env.SKIP_UPGRADE != 'true' }}
      uses: ./.github/actions/e2e-upgrade
      with:
        cluster-config-data: ${{ secrets.E2E_CLUSTER_CONFIG }}
        cluster-kube-config-data: ${{ secrets.E2E_KUBE_CONFIG }}

    - name: Builder Tests (S2I)
      if: ${{ always() && env.SKIP_BUILDER != 'true' }}
      uses: ./.github/actions/e2e-builder
      with:
        cluster-config-data: ${{ secrets.E2E_CLUSTER_CONFIG }}
        cluster-kube-config-data: ${{ secrets.E2E_KUBE_CONFIG }}
        publisher: "S2I"

    - name: KNative Tests
      if: ${{ always() && env.SKIP_KNATIVE != 'true' }}
      uses: ./.github/actions/e2e-knative
      with:
        cluster-config-data: ${{ secrets.E2E_CLUSTER_CONFIG }}
        cluster-kube-config-data: ${{ secrets.E2E_KUBE_CONFIG }}

    - name: Kubernetes Tests
      if: ${{ always() && env.SKIP_KUBERNETES != 'true' }}
      uses: ./.github/actions/e2e-kubernetes
      with:
        cluster-config-data: ${{ secrets.E2E_CLUSTER_CONFIG }}
        cluster-kube-config-data: ${{ secrets.E2E_KUBE_CONFIG }}
